from pathlib import Path
import json,html,shutil
r=Path(__file__).parent;d=json.loads((r/'content.json').read_text());e=html.escape
icons={'arrow':'<path d="M7 17 17 7M7 7h10v10"/>','folder':'<path d="M3 7V5h6l2 3h10v12H3z"/>','code':'<path d="m8 7-5 5 5 5m8-10 5 5-5 5m-3-14-2 18"/>','shield':'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8 12 3 3 5-6"/>','spark':'<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5z"/>','mail':'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>','terminal':'<path d="m4 5 7 7-7 7m9 0h7"/>','pin':'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>','book':'<path d="M12 6C7 2 3 4 3 4v15s4-2 9 2c5-4 9-2 9-2V4s-4-2-9 2Zm0 0v15"/>','award':'<circle cx="12" cy="8" r="5"/><path d="m8 12-2 9 6-3 6 3-2-9"/>','hash':'<path d="M9 3 7 21M17 3l-2 18M3 8h18M2 16h18"/>','heart':'<path d="M20 5c-3-3-7-1-8 1-1-2-5-4-8-1-5 5 8 15 8 15S25 10 20 5Z"/>','close':'<path d="m6 6 12 12M6 18 18 6"/>'}
def icon(n):return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[n]+'</svg>'
logos={'Python':'python','C++':'cplusplus','Java':'java','JavaScript':'javascript','HTML':'html5','Windows APIs':'windows','Linux':'linux','Git':'git','Node.js':'nodejs','FastAPI':'fastapi','TensorFlow':'tensorflow','Keras':'keras','NumPy':'numpy','Streamlit':'streamlit','Plotly':'plotly','Arch Linux':'archlinux','Bash':'bash','React':'react','SQLite':'sqlite'}
logos.update({'Next.js':'nextjs','TypeScript':'typescript','Tailwind CSS':'tailwindcss','YARA': 'yara', 'Entropy analysis': 'entropy', 'Heuristic detection': 'heuristics', 'Network security': 'network-security', 'Cryptography': 'cryptography', 'MITRE ATT&CK': 'mitre', 'Embedded systems': 'embedded', 'IoT': 'iot', 'IoT architecture': 'iot', 'Sensor fusion': 'sensor-fusion', 'REST APIs': 'rest-api', 'SHAP': 'shap', 'Data structures & algorithms': 'algorithms', 'OOP': 'oop', 'Design patterns': 'patterns', 'Concurrency': 'concurrency', 'OS internals': 'os-internals', 'Signal processing': 'signal', 'DSP': 'dsp'})
# Resolve real local filenames instead of inventing image paths.
files=[p.name for p in (r/'dist/technologies').glob('*.svg')]
def tech(n):
 stem=logos.get(n,'');filename=next((f for f in files if f.split('.')[0].lower()==stem.lower()),None)
 return '<span class="tech '+('logo-tech' if filename else 'concept-tech')+'" tabindex="0" title="'+e(n)+'">'+('<img src="technologies/'+filename+'" alt="'+e(n)+'" width="26" height="26">' if filename else icon('code'))+'<span class="tech-label">'+e(n)+'</span></span>'
colors=['purple','pink','mint']
project_cards=''
for i,p in enumerate(d['projects']):
 project_cards+=f'''<article class="folder project-folder {colors[i]}"><div class="folder-tab">0{i+1} / {['SECURITY','AI SECURITY','MACHINE LEARNING'][i]}</div><button class="project-open" data-project="{i}" aria-label="View {e(p['name'])} project details"><div class="project-art"><span class="project-symbol">{icon(['shield','spark','code'][i])}</span><span class="stamp">{e(p['status'])}</span><span class="project-no" aria-hidden="true">0{i+1}</span></div><div class="project-copy"><h3>{e(p['name'])}</h3><p>{e(p['description'])}</p><span class="card-open">Open project {icon('arrow')}</span></div></button><div class="project-tech">{''.join(tech(t) for t in p['tags'])}</div></article>'''
skill_cards=''
for i,(category,names) in enumerate(d['skills']):
 skill_cards+=f'<article class="folder skill-folder { ["pink","yellow","mint","purple","blue","lime"][i] }"><div class="folder-tab">{icon(["shield","code","terminal","folder","spark","book"][i])}</div><h3>{e(category)}</h3><div class="skill-icons">'+''.join(tech(n) for n in names)+'</div></article>'
social=''.join(f'<a href="{e(url)}" target="_blank" rel="noreferrer" aria-label="{e(name)}" title="{e(name)}"><img src="social/{name.lower()}.svg" alt="" width="26" height="26"><span class="social-tooltip">{e(name)}</span></a>' for name,url in d['socialLinks'])
certs=''.join(f'<li><span>{icon("award")}</span><div><strong>{e(name)}</strong><small>{e(issuer)}</small></div></li>' for name,issuer in d['certifications'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#ffca05"><title>Manthan Garg — Build. Explore. Repeat.</title><meta name="description" content="Manthan Garg’s portfolio: cybersecurity, Linux, systems, machine learning and IEEE leadership. Explore the projects and meet the person behind them."><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="preload" href="fonts/Anton-Regular.ttf" as="font" type="font/ttf" crossorigin><script src="themes.js"></script><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="appearance.css"><script src="content.js" defer></script><script src="app.js" defer></script><script src="companions.js" defer></script><script src="neko.js" defer></script><script src="clicks.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a>
<div class="site-wrap"><header class="topbar"><a class="brand" href="#home" aria-label="More with Manthan home"><span class="brand-icon">m.</span><span>morewithmanthan</span></a><button class="theme-toggle" id="theme-toggle" type="button" aria-label="Customize theme" aria-haspopup="dialog"><span class="theme-toggle-swatch" aria-hidden="true"></span><span class="theme-toggle-label">Theme</span></button><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#journey">Journey</a><a class="nav-contact" href="#contact">Let’s talk @@arrow@@</a></nav></header>
<main id="main"><section class="hero" id="home"><div class="hero-copy"><p class="eyebrow"><span class="tiny-star">✳</span> CYBERSECURITY · SYSTEMS · CURIOSITY</p><h1>BUILD.<br>EXPLORE.<br><span class="outlined">REPEAT.</span></h1><p class="intro">Hey, I’m <strong>Manthan Garg.</strong><br>I build security tools, explore Linux internals, and turn ideas into things that work.</p><div class="hero-actions"><a class="button black" href="#work">Explore my work @@arrow@@</a><a class="button cream" href="assets/Manthan_Garg_Resume.pdf" target="_blank" rel="noreferrer">Resume / CV @@book@@</a></div><a class="hero-email" href="mailto:linkwithmanthan@gmail.com">@@mail@@ linkwithmanthan@gmail.com</a></div>
<div class="hero-visual"><div class="blob pink-blob" aria-hidden="true"></div><div class="blob purple-blob" aria-hidden="true"></div><div class="profile-card"><div class="card-bar"><span>THE PERSON BEHIND THE PROJECTS</span>@@spark@@</div><div class="portrait-stage"><button class="portrait-sticker" id="hello-secret" title="Say hello">Hello, world!</button><img src="assets/manthan-pixel.png" width="1254" height="1254" alt="Pixel portrait of Manthan Garg"><span class="portrait-mark" aria-hidden="true">✳</span></div><div class="profile-caption"><h2>Manthan Garg</h2><p>Student. Builder. Forever curious.</p><span>@@pin@@ Chandigarh, India</span></div></div><div class="floating-note">A little curiosity.<br>A lot of building.</div></div></section>
<ul class="interest-strip" aria-label="Interests"><li><img src="technologies/linux.svg" alt="" width="28" height="28"><span>Linux</span></li><li>@@shield@@<span>Cybersecurity</span></li><li><img src="social/github.svg" alt="" width="28" height="28"><span>Open source</span></li><li>@@code@@<span>Building things</span></li><li>@@heart@@<span>Community</span></li></ul>
<section class="work section" id="work"><div class="section-head"><div><p class="eyebrow">01 / MY PROJECT FOLDERS</p><h2>IDEAS, PUT TO WORK.</h2></div><span class="label cream">3 projects. Plenty of curiosity.</span></div><div class="project-grid">@@projects@@</div><div class="section-bottom"><a class="text-link" href="https://github.com/MoreWithManthan?tab=repositories" target="_blank" rel="noreferrer">More on GitHub @@arrow@@</a></div></section>
<section class="about section" id="about"><div class="about-copy"><p class="eyebrow">02 / MORE THAN A README</p><h2>CURIOUS BY DEFAULT.<br>HANDS-ON BY CHOICE.</h2><p>I’m a Computer Science Engineering student at CSOET, Himachal Pradesh, drawn to the way things work under the hood.</p><p>My interests live somewhere between cybersecurity, Linux, and building useful software. I like turning old hardware into fast development machines and turning “what if?” into something I can test.</p><p>Outside my own projects, I help bring people together through the IEEE Student Branch as Vice Chair.</p><div class="about-tags"><span>Arch Linux</span><span>Open source</span><span>Always learning</span></div></div><div class="notes-stack"><article class="note yellow-note"><span class="note-pin" aria-hidden="true"></span><p class="eyebrow">CURRENTLY EXPLORING</p><h3>What’s happening<br>under the hood?</h3><p>OS internals, endpoint threat detection, networking, and low-level systems.</p>@@terminal@@</article><article class="note mint-note"><p class="eyebrow">A LITTLE PERSONAL</p><p>Old hardware.<br>A fresh Linux install.<br><strong>A very good afternoon.</strong></p>@@heart@@</article></div></section>
<section class="section tools" id="stack"><div class="section-head"><div><p class="eyebrow">03 / THE TOOLBOX</p><h2>TOOLS I REACH FOR.</h2></div><span class="label lime">Learn it. Use it. Build with it.</span></div><div class="skill-grid">@@skills@@</div></section>
<section class="journey section" id="journey"><div class="section-head"><div><p class="eyebrow">04 / LEARNING & LEADING</p><h2>THE STORY SO FAR.</h2></div>@@spark@@</div><div class="journey-board"><article><span class="journey-index">01</span><div><p class="eyebrow">2024 — 2028</p><h3>CSOET, Himachal Pradesh</h3><p>B.E. Computer Science Engineering · CGPA 8.34</p><p class="secondary">Network security, cryptography, operating systems, data structures, and object-oriented programming.</p></div>@@book@@</article><article><span class="journey-index">02</span><div><p class="eyebrow">COMMUNITY & LEADERSHIP</p><h3>IEEE Student Branch</h3><p>Vice Chair · CSOET, Himachal Pradesh</p><p class="secondary">Technical events, volunteer coordination, cross-chapter collaboration, and welcoming freshers with hands-on activities.</p></div>@@code@@</article><article><span class="journey-index">03</span><div><p class="eyebrow">BEYOND THE CAMPUS</p><h3>IEEE Delhi SAC & IOC Team</h3><p>Team member</p><p class="secondary">Regional student activities and outreach, including sponsorship outreach and the official IEEE DSSYWLC 2025 brochure.</p></div>@@folder@@</article></div><div class="milestones"><div class="milestone pink">@@award@@<div><strong>Published patent</strong><span>NeuroSole · Smart healthcare wearable</span></div></div><div class="milestone purple">@@spark@@<div><strong>Top 5 · Buildathon</strong><span>Emergence’26</span></div></div></div><details class="certificates"><summary>Certifications <span>Open folder +</span></summary><ul>@@certs@@</ul></details></section>
<section class="lab section" id="lab"><div><p class="eyebrow">05 / THE PLAYGROUND</p><h2>GO ON.<br>POKE AROUND.</h2><p>A small corner for the curious. Open a terminal, try a tiny CTF, or calculate a hash. Everything runs in your browser.</p></div><div class="lab-cards"><button class="lab-card cream" data-lab="terminal">@@terminal@@<span><strong>Terminal</strong><small>Meet the portfolio, command by command.</small></span>@@arrow@@</button><button class="lab-card yellow" data-lab="ctf">@@shield@@<span><strong>Capture the flag</strong><small>12 flags. Three projects. Hints included.</small></span>@@arrow@@</button><button class="lab-card mint" data-lab="hash">@@hash@@<span><strong>Hash calculator</strong><small>Text in. SHA-256 out.</small></span>@@arrow@@</button></div></section>
<section class="contact section" id="contact"><span class="contact-star" aria-hidden="true">✳</span><p class="eyebrow">06 / YOUR NEXT GOOD IDEA</p><h2>LET’S BUILD<br>SOMETHING GOOD.</h2><p>Have a project, an open-source idea, or something interesting to share?</p><a class="button black" href="mailto:linkwithmanthan@gmail.com">Email me @@mail@@</a><div class="social-links">@@social@@</div></section></main><footer><a class="brand" href="#home"><span class="brand-icon">m.</span><span>morewithmanthan</span></a><button class="companion-settings" id="companion-settings">Companion settings</button><button class="companion-settings" id="sound-toggle" type="button" aria-pressed="true">Click sounds: on</button><span>© <span id="year">2026</span> Manthan Garg</span><a href="#home">Back to top ↑</a></footer></div>
<dialog id="project-dialog" class="project-dialog" aria-labelledby="detail-title"><div class="dialog-head"><span id="project-count" aria-live="polite" aria-atomic="true">PROJECT 1 OF 3</span><button class="square close-dialog" aria-label="Close project">@@close@@</button></div><div id="project-detail"></div><div class="dialog-nav"><button class="round" id="previous-project" aria-label="Previous project">←</button><span>Explore projects <small>Use ← and → keys</small></span><button class="round yellow" id="next-project" aria-label="Next project">→</button></div></dialog>
<dialog id="lab-dialog" class="lab-dialog" aria-labelledby="lab-title"><div class="dialog-head"><strong id="lab-title">THE PLAYGROUND</strong><button class="square close-dialog" aria-label="Close playground">@@close@@</button></div><div id="lab-body"></div></dialog><div id="toast" role="status" aria-live="polite"></div></body></html>'''
for name in icons:page=page.replace('@@'+name+'@@',icon(name))
for k,v in {'projects':project_cards,'skills':skill_cards,'certs':certs,'social':social}.items():page=page.replace('@@'+k+'@@',v)
(r/'dist/index.html').write_text(page)
(r/'dist/content.js').write_text('window.portfolioData = '+json.dumps(d)+';\n')
(r/'dist/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect x="5" y="5" width="54" height="54" rx="12" fill="#ffca05" stroke="#151515" stroke-width="5"/><text x="13" y="45" font-family="Arial,sans-serif" font-size="43" font-weight="900">m</text></svg>')
